// team_c_04: global std::string arrays (dynamic initializers)
// NOTE: names are placeholders keyed by original addresses; literals/order are exact.
#include <string>

extern std::string gameString_cf4db4;	// global_strings.cpp

// Initializer 0xb2a8d0, array 0xd1f720, 97 x std::string.
std::string gameStrings_d1f720[97] =
{
	"Cogmind",
	"Worker",
	"Builder",
	"Tunneler",
	"Hauler",
	"Recycler",
	"Carrier",
	"Minesweeper",
	"Mechanic",
	"Operator",
	"Drone",
	"Turret",
	"Watcher",
	"Swarmer",
	"Cutter",
	"Saboteur",
	"Grunt",
	"Brawler",
	"Duelist",
	"Protector",
	"Researcher",
	"Sentry",
	"Demolisher",
	"Specialist",
	"Hunter",
	"Programmer",
	"Heavy",
	"Q-Series",
	"Behemoth",
	"Compactor",
	"Striker",
	"Executioner",
	"Alpha 7",
	"Fortress",
	"V-Series",
	"Artisan",
	"Cobbler",
	"Subdweller",
	"Bolteater",
	"Federalist",
	"Explorer",
	"Ranger",
	"Guru",
	"Scientist",
	"Zionite",
	"Z-Light",
	"Z-Heavy",
	"Z-EX",
	"Samaritan",
	"Tinkerer",
	"Demented",
	"Furnace",
	"Parasite",
	"Thief",
	"Assembler",
	"Assembled",
	"Golem",
	"Fireman",
	"Mutant",
	"Knight",
	"Troll",
	"Dragon",
	"Hydra",
	"Borebot",
	"Unchained",
	"Revision",
	"Abomination",
	"Anomaly",
	"Player",
	"R17",
	"Combat R17",
	"Imprinter",
	"Triborg",
	"Optimus",
	"A2",
	"A3",
	"A4",
	"A5",
	"A6",
	"A7",
	"A8",
	"Zhirov",
	"Perun",
	"Svarog",
	"Data Miner",
	"God Mode",
	"Warlord",
	"Old Warlord",
	"Sigix Pod",
	"Sigix",
	"MAIN.C",
	"Architect",
};

// Initializer 0xb2f550, array 0xd2ae30, 39 x std::string.
std::string gameStrings_d2ae30[39] =
{
	gameString_cf4db4 + "ZION-ROSTER",
	gameString_cf4db4 + "ZION-DISPATCH-1",
	gameString_cf4db4 + "ZION-DISPATCH-2",
	gameString_cf4db4 + "ZION-DISPATCH-3",
	gameString_cf4db4 + "ZION-DISPATCH-4",
	gameString_cf4db4 + "ZION-DISPATCH-5",
	gameString_cf4db4 + "ZION-DISPATCH-6",
	gameString_cf4db4 + "ZION-INTEL",
	gameString_cf4db4 + "ZION-SEEK-1",
	gameString_cf4db4 + "ZION-SEEK-2",
	gameString_cf4db4 + "ZION-SEEK-3",
	gameString_cf4db4 + "ZION-SEEK-4",
	gameString_cf4db4 + "ZION-REPORT",
	"EXILES_VAULT",
	"EXILES_VAULT_DESTROYED",
	"RECYCLING_ACCESS",
	"DEEP_ACCESS_1",
	"DEEP_ACCESS_2",
	"DEEP_ACCESS_3",
	"DEEP_ACCESS_4",
	"DEEP_ACCESS_1_INTERCEPTED",
	"DEEP_ACCESS_2_INTERCEPTED",
	"DEEP_ACCESS_3_INTERCEPTED",
	"DEEP_ACCESS_4_INTERCEPTED",
	"ARCHITECT_HELP_FROM_A8",
	"CETUS_MANUFACTURE",
	"DECONSTRUCTOR_DOOR",
	"WARLORD_STASH",
	"LAB_ACCESS",
	"SIGIX_ACCESS",
	"L2_POWER_CELL",
	"COM_CAVE_SEALS",
	"GLITCHMAP_INVERT",
	"GLITCHMAP_PIXEL",
	"GLITCHMAP_NOISE",
	"GLITCHMAP_HIDEWALLS",
	"DESTROY",
	"EXPLODE",
	"FLUFFTEST",
};
// Initializer 0xb2f8f0, array 0xcf0470, 39 x std::string.
std::string gameStrings_cf0470[39] =
{
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"You can't open the door any more than it's already open.",
	"You can't open the door any more than it's already open.",
	"Door's open, idiot. Go through it. --A4",
	"You did that already...",
	"Feeling alright?",
	"Go look around the corner. It's already open.",
	"You REALLY want that door open, don't you.",
	"You did that already...",
	"Feeling alright?",
	"Go look around the corner. It's already open.",
	"You REALLY want that door open, don't you.",
	"Sorry, you've reached your support quota.",
	"Resources insufficient.",
	"Door open.",
	"Door open.",
	"Door open.",
	"Quarantine Chamber open.",
	"Countdown already initiated.",
	"Disengage process already initiated.",
	"",
	"",
	"",
	"",
	"",
	"",
};
