// team_c_30: effect description builder (0x55f080): writes the description text for one of 219 effect types
// NOTE: placeholder names; only the members it reads are declared
#include <string>
#include <vector>
using namespace std;

string intToString(int value);
int OpX5_minInt(int a, int b);	// NOTE: placeholder name (op_x5.cpp)
string OpY1_intToStringSigned(int value);	// 0x405560
string OpY1_floatToStringSigned(float value, int unknown1, int unknown2);
string &OpY1_eraseFirstCharRef(string &s);
string opw8_countString(int count, const string &noun);	// 0x407a80
int stringToInt(const string &text);
bool opU1_extractParens(string &text, string &inside);	// 0x436d80
int OpT8a_findStringIndex(const string *list, unsigned int count, string s);
int OpT8a_sumVector(vector<int> &v);
void c30_split(const string &text, char separator, vector<string> &out);	// NOTE: placeholder name (0x408700)
extern string gameStrings_cf40c8[], gameStrings_d323f8[], gameStrings_d30428[], gameStrings_d378d0[];	// global_string_arrays.cpp
struct C30_Rec { char pad[0x1ac]; string f1ac; };	// NOTE: placeholder layout
int OpU8a_indexOfName4(vector<C30_Rec *> &v, string &name);
extern vector<C30_Rec *> g_d25de0;	// NOTE: placeholder name

class C30_Effect	// NOTE: placeholder name/layout (OpS2_Target in op_s2.cpp)
{
public:
	char pad0[0x8];
	string f8;
	string f24;
	char pad40[0x44 - 0x40];
	int f44;
	int f48;
	int f4c;
	int f50;
	char pad54[0xb4 - 0x54];
	float fb4;
	char padb8[0xf0 - 0xb8];
	int type;	// +0xf0
	int ff4;	// +0xf4
	int ff8;
	int ffc;
	char pad100[0x1b4 - 0x100];
	string f1b4;

	int getValue457330(int index);	// NOTE: folded with OpR1e_RecLists::getValue457330
	C30_Rec *getRecord();	// NOTE: folded with TeamB_56f3c0::getRecord
	bool unknown56fc30(vector<int> &out);	// NOTE: folded with OpR2c_Config::unknown56fc30
	void describe(string &out);
};
extern int g_b961cc;	// NOTE: placeholder name
extern bool g_d28d16;	// NOTE: placeholder name
extern const float c30_ba09e0, c30_ba0a88, c30_ba0a8c, c30_ba0b60, c30_ba0bb4, c30_bba054;	// NOTE: placeholder names (named float constants in .rdata)

void C30_Effect::describe(string &out)
{
	switch (type)
	{
	case 0:	// 0079
		break;
	case 1:	// 007e
		out = "Dissipates " + intToString(ff4) + " heat per turn.\n <stacks>";
		break;
	case 2:	// 0147
		out = "Dissipates " + intToString(ff4) + " heat per turn, losing " + intToString(2) + " integrity in the process, but is applied after all standard heat dissipation, and only when heat levels rise to at least " + intToString(g_b961cc) + ".\n <stacks>";
		break;
	case 3:	// 0391
		out = "Reduces total heat generated by a multi-weapon volley by " + intToString(ff4) + "%, losing " + intToString(1) + " integrity in the process. Volley must contain two or more heat-generating weapons.\n <no_stack>";
		break;
	case 4:	// 0524
		out = "Dissipates heat each turn, losing " + intToString(1) + " integrity per " + intToString(ff4) + " heat dissipated, applied after all standard heat dissipation and any injectors, and only when heat levels rise above " + intToString(g_b961cc) + ". If multiple similar parts attached, heat is distributed among them equally where possible.\n <stacks>";
		break;
	case 5:	// 0774
		out = "Dissipates heat each turn, causing " + intToString(1) + " damage per " + intToString(ff4) + " heat dissipated, applied after all standard heat dissipation and any injectors, and only when heat levels rise above " + intToString(g_b961cc) + ". The damage is applied to other attached parts, selected randomly, in chunks of " + intToString(5) + ". Also reduces effect of incoming heat transfer by one level.\n <no_stack>";
		break;
	case 6:	// 0a7b
		out = "Lowers base temperature to " + intToString(-ff4) + ". Also doubles the cooling effect of all active Heat Sinks (includes regular/Mak/Imp/Adv/Exp/Cep), protects power sources from forced shutdown while overheating, and has a " + intToString((ff4 / 10) + 15) + "% chance to prevent other types of overheating side effects.\n <no_stack>";
		break;
	case 7:	// 0c26
		out = "Increases inventory capacity by " + intToString(ff4) + ".\n <no_stack>";
		break;
	case 8:	// 0d01
		out = "Increases energy storage capacity by " + intToString(ff4) + ". Also stores surplus generated energy while in inventory, but cannot be accessed for use until attached. Stored energy can also be extracted directly if on the ground at current position. Storage and retrieval while not attached is not possible if this item is corrupted.\n <stacks>";
		break;
	case 9:	// 0ddc
		out = "Increases matter storage capacity by " + intToString(ff4) + ". Also stores surplus collected matter while in inventory, but cannot be accessed for use until attached. Stored matter can also be extracted directly if on the ground at current position. Storage and retrieval while not attached is not possible if this item is corrupted.\n <stacks>";
		break;
	case 10:	// 0eb7
		out = "Increases visual sensor range by " + intToString(ff4) + ".\n <no_stack>";
		break;
	case 11:	// 0f92
		out = "Enables robot scanning up to a distance of " + intToString(ff4) + ", once per turn.";
		break;
	case 12:	// 106d
		out = (ff4 == 1 ? "Strength 1: Robot scan signals differentiate between object sizes." : (ff4 == 2 ? "Strength 2: Robot scan signals accurately reflect target size and class, and are unaffected by system corruption." : (ff4 == 3 ? "Strength 3: Robot scan signals accurately reflect target size and specific class rating, and are unaffected by system corruption." : "Strength 4: Robot scan signals accurately reflect target size and specific class rating, are unaffected by system corruption, and can discern dormant, unpowered, disabled, and broken robots.")));
		out += " (Requires data from a Sensor Array.) Also enables deciphering of signals emitted from adjacent exits, revealing where they lead, and at garrisons know the time until the next response dispatch, if any. When multiple exits lead to the same destination, after having identified the first, subsequent ones will be identified on sight even without an interpreter.";
		break;
	case 13:	// 1101
		out = "Enables robot scanning up to a distance of " + intToString(ff4) + ", once per turn, in addition to all effects of a maximum-strength Signal Interpreter. Immune to all jamming, scrambling and cloaking effects except robots with Scan Cloak 5. Also detects long-term residual evidence of prior robot activity within field of view. 0b10 combat robots scanned by this device will report the event, once per bot.";
		break;
	case 14:	// 11dc
		out = "Enables friend-or-foe identification of active robots up to a distance of " + intToString(ff4) + ", once per " + intToString(2) + " turns. Yellow markers are 0b10-affiliated signals, blue markers are not.";
		break;
	case 15:	// 136f
		out = "Enables real-time tracking of all 0b10 combat and non-combat robots across the entire floor. Only applies in 0b10-controlled areas.";
		break;
	case 16:	// 1381
		out = "Enables terrain scanning up to a distance of " + intToString(ff4) + ", once per turn.";
		break;
	case 17:	// 145c
		out = "Increases terrain scanning density by " + intToString(ff4) + ". (Requires data from a Terrain Scanner.)\n <stacks>";
		break;
	case 18:	// 1537
		out = "Enables real-time seismic detection and analysis up to a distance of " + intToString(ff4) + ".\n <no_stack>";
		break;
	case 19:	// 1612
		out = "Increases difficulty of long-distance tracking by hostile robots, causing them to lose your position " + intToString(ff4 + 1) + "x as quickly outside line of sight. Also prevents alert increases caused by 0b10 pursuers losing track of you.\n <stacks>";
		break;
	case 20:	// 16f0
		out = "Blocks local transmissions from visible hostiles within a range of " + intToString(ff4) + ", making it impossible for them to share information about your current position. Jamming has a small chance to fail, where the chance is dependent on the type of hostile being jammed. Also prevents calls for reinforcements, and suppresses alarm traps. Visibility for jamming purposes includes indirect knowledge via drones, Watcher Feeds, and so on, but must still be within the indicated range from you personally.";
		break;
	case 21:	// 17cb
		out = "Boost the effect of Transmission Jammers to prevent random failure to jam.";
		break;
	case 22:	// 17dd
		out = "Enables real-time tracking of 0b10 Haulers across the entire floor. Only applies in 0b10-controlled areas.";
		break;
	case 23:	// 17ef
		out = "Enables both real-time tracking of 0b10 Haulers across the entire floor, and gives access to their current manifest. Toggle active state to temporarily list all inventories in view. Only applies in 0b10-controlled areas.";
		break;
	case 24:	// 1801
		out = "Scans all visible walls to analyze the structure behind them, out to a depth of " + intToString(ff4) + ". Also identifies hidden doorways and highlights areas that will soon cave in due to instability even without further stimulation.";
		break;
	case 25:	// 18dc
		out = intToString(ff4 + 1) + "% chance to detect each hidden trap within field of view, checked each turn on a per-trap basis. Also " + intToString(ff8) + "% chance to detect and immediately disarm a hidden hostile trap if moving adjacent to one, but no more than one per move. The same chance and effect are applied to each known hostile trap at or adjacent to current location once per two turns.\n <parallel_ok>";
		break;
	case 26:	// 1a3d
		out = "Analyzes visible machines to locate others on the 0b10 network. Also determines whether an explosive machine has been destabilized and how long until detonation.";
		break;
	case 27:	// 1a4f
		out = "Links to the Forge Plexus, every " + intToString(ff4) + " turns receiving positions and IDs of all 0b10-recognized parts through the entire Protoforge area.";
		break;
	case 28:	// 1b2a
		out = "Reasons likely distance at which each visible hostile can spot you, enables predictions of visible robot travel paths, and analyzes ambient signals to determine how many hostiles are currently tracking you, as well as pinpoint them if within a range of " + intToString(ff4) + ".";
		break;
	case 29:	// 1c05
		out = "Analyzes ambient 0b10 signals to gauge the current alert level, and reduces all influence increases by " + intToString(ff4) + "%.\n <no_stack>";
		break;
	case 30:	// 1ce0
		out = "Effective sight range of robots attempting to spot you reduced by " + intToString(ff4) + ". Also -" + intToString(ff4 << 2) + "% chance of being noticed by hostiles if passing through their field of view when not their turn.\n <half_stack>";
		break;
	case 31:	// 1e81
		out = "While active, not considered a threat to Complex 0b10, but loses validity with each move. Validity expires more quickly while moving in view of 0b10 combat or security bots, and attacking any target immediately invalidates the mask. Also prevents Complex 0b10 traps from triggering.";
		break;
	case 32:	// 1e93
		out = "Reinforcements dispatched by Heavies due to sensor detection of anyone using a Spoofer instead target some area on the opposite side of the Heavy from where the actual detection is made, where possible, or at closest will target the Heavy's position itself.";
		break;
	case 33:	// 1ea5
		out = "Increases generation of power sources by " + intToString(ff4) + "%.\n <stacks>";
		break;
	case 34:	// 1f80
		out = "Increases mass support by " + intToString(ff4) + ".\n <no_stack>";
		break;
	case 35:	// 205b
		out = "Increases active wheel/leg/tread speed by " + intToString(ff4) + "%.\n <no_stack>";
		break;
	case 36:	// 2136
		out = "Increases active leg speed by " + intToString(ff4) + "%.\n <no_stack>";
		break;
	case 37:	// 2211
		out = "Increases active wheel speed by " + intToString(ff4) + "%, if not overweight.\n <no_stack>";
		break;
	case 38:	// 22ec
		out = "Doubles core/hover/flight speed, applied before considering any overweight penalties.\n <no_stack>";
		break;
	case 39:	// 22fe
		out = "Reduces time to transition into or out of siege mode by " + intToString(ff4) + " turns. Transitioning always requires at least 1 turn.\n <stacks>";
		break;
	case 40:	// 23d9
		out = "Raises the threshold for side effects of overheating to " + intToString(ff4) + ".\n <no_stack>";
		break;
	case 41:	// 24b4
		out = "All attached parts gain immunity to disruption attacks. Cuts chance of system corruption from electromagnetic damage by " + intToString(100 - (100 / ff4)) + "%. Also a " + intToString(ff4 * 0xa) + "% chance to prevent the effects of a shock or surge trap.\n <stacks>";
		break;
	case 42:	// 2662
		out = "Reduces effective system corruption by " + intToString(ff4) + ".\n <stacks>";
		break;
	case 43:	// 273d
		out = "Prevents infliction of new system corruption from any external source, losing " + intToString(2) + " integrity per percent of corruption blocked.";
		break;
	case 44:	// 280d
		out = "Prevent " + intToString(ff4) + "% of heat caused by thermal damage.\n <stacks>";
		break;
	case 45:	// 28e8
		out = "Reduces part disable durations, dividing them by " + intToString(ff4) + ".\n <no_stack>";
		break;
	case 46:	// 29c3
		out = "Protects other parts via high coverage.";
		break;
	case 47:	// 29d5
		out = "Enables kinetic damage resistance: " + intToString(ff4) + "%.\n <no_stack>";
		break;
	case 48:	// 2ab0
		out = "Enables thermal damage resistance: " + intToString(ff4) + "%.\n <no_stack>";
		break;
	case 49:	// 2b8b
		out = "Enables explosive damage resistance: " + intToString(ff4) + "%.\n <no_stack>";
		break;
	case 50:	// 2c66
		out = "Enables electromagnetic damage resistance: " + intToString(ff4) + "%.\n <no_stack>";
		break;
	case 51:	// 2d41
		out = "Enables impact damage resistance: " + intToString(ff4) + "%.\n <no_stack>";
		break;
	case 52:	// 2e1c
		out = "Enables slashing damage resistance: " + intToString(ff4) + "%.\n <no_stack>";
		break;
	case 53:	// 2ef7
		out = "Enables piercing damage resistance: " + intToString(ff4) + "%.\n <no_stack>";
		break;
	case 54:	// 2fd2
		out = "Enables resistance against all standard forms of damage: " + intToString(ff4) + "%.\n <no_stack>";
		break;
	case 55:	// 30ad
		out = "Enables thermal damage resistance: " + intToString(ff4) + "%, applying benefit to both self and any allies within a range of " + intToString(10) + ".\n <no_stack>";
		break;
	case 56:	// 3240
		out = "Caps the amount of system corruption from any single external source to " + intToString(ff4) + ", applying benefit to both self and any allies within a range of " + intToString(10) + ". External sources include attacks and trap effects, whereas inapplicable internal sources include impact-based destruction and attaching corrupted parts.\n <no_stack>";
		break;
	case 57:	// 33d3
		out = "Absorbs " + intToString(ff4) + "% of damage that would otherwise affect core. Also negates extra effects of critical strikes against core, but cannot protect against overflow damage.\n <no_stack>";
		break;
	case 58:	// 34ae
		out = "Absorbs " + intToString(ff4) + "% of damage that would otherwise affect power sources. Also negates extra effects of critical strikes against power sources, and prevents chain reactions due to electromagnetic damage, but cannot protect against overflow damage.\n <no_stack>";
		break;
	case 59:	// 3589
		out = "Absorbs " + intToString(ff4) + "% of damage that would otherwise affect propulsion units. Also negates extra effects of critical strikes against propulsion units, but cannot protect against overflow damage.\n <no_stack>";
		break;
	case 60:	// 3664
		out = "Absorbs " + intToString(ff4) + "% of damage that would otherwise affect utilities. Does not protect parts of the Protection type, and cannot protect against overflow damage, but negates extra effects of critical strikes against utilities.\n <no_stack>";
		break;
	case 61:	// 373f
		out = "Absorbs " + intToString(ff4) + "% of damage that would otherwise affect weapons. Also negates extra effects of critical strikes against weapons, but cannot protect against overflow damage.\n <no_stack>";
		break;
	case 62:	// 381a
		out = "Muliplies coverage of all armor by " + intToString(ff4) + ". Takes precedence over effect of treads siege mode on armor coverage.\n <no_stack>";
		break;
	case 63:	// 38f5
		out = "Blocks 50% of damage to this part in exchange for energy loss at a 1:" + intToString(ff4) + " ratio (no effect if insufficient energy).\n\nExample, 20 damage inflicted on this part would be reduced to 10, draining 10 energy to prevent the rest.";
		break;
	case 64:	// 39d0
		out = "While active, " + intToString(ff4) + "% of damage to this part is instead passed along to the core.";
		break;
	case 65:	// 3aab
		out = intToString(ff4) + "% of damage to parts is instead transferred directly to the core.\n <stacks>";
		break;
	case 66:	// 3b46
		out = "Reduces damage of each incoming kinetic or thermal projectile by " + intToString(ff4) + " (only usable if no active force fields, shield generators, remote shields, or energy mantles).\n <no_stack>";
		break;
	case 67:	// 3c21
		out = "Blocks 25% of damage in exchange for energy loss at a 1:" + intToString(ff4) + " ratio (no effect if insufficient energy)\n <no_stack>\n\nExample: A 20-damage attack would be reduced to 15 (20-(20*0.25)=15), draining " + intToString(ff4 * 5) + " energy to prevent the rest (5*" + intToString(ff4) + "=" + intToString(ff4 * 5) + ").";
		break;
	case 68:	// 3f4b
		out = "Blocks 50% of damage in exchange for energy loss at a 1:" + intToString(ff4) + " ratio (no effect if insufficient energy).\n <no_stack>\n\nExample: A 20-damage attack would be reduced to 10 (20-(20*0.50)=10), draining " + intToString(ff4 * 0xa) + " energy to prevent the rest (10*" + intToString(ff4) + "=" + intToString(ff4 * 0xa) + ").";
		break;
	case 69:	// 4275
		out = "Blocks 75% of damage in exchange for energy loss at a 1:" + intToString(ff4) + " ratio (no effect if insufficient energy).\n <no_stack>\n\nExample: A 20-damage attack would be reduced to 5 (20-(20*0.75)=5), draining " + intToString(ff4 * 0xf) + " energy to prevent the rest (15*" + intToString(ff4) + "=" + intToString(ff4 * 0xf) + ").";
		break;
	case 70:	// 459f
		out = "Blocks 25% of damage to self and any visible allies within a range of " + intToString(10) + " in exchange for energy loss at a 1:" + intToString(ff4) + " ratio.\n <no_stack>\n\nExample: A 20-damage attack would be reduced to 15 (20-(20*0.25)=15), draining " + intToString(ff4 * 5) + " energy to prevent the rest (5*" + intToString(ff4) + "=" + intToString(ff4 * 5) + ").";
		break;
	case 71:	// 4987
		out = "Blocks 50% of damage to self and any visible allies within a range of " + intToString(10) + " in exchange for energy loss at a 1:" + intToString(ff4) + " ratio.\n <no_stack>\n\nExample: A 20-damage attack would be reduced to 10 (20-(20*0.50)=10), draining " + intToString(ff4 * 0xa) + " energy to prevent the rest (10*" + intToString(ff4) + "=" + intToString(ff4 * 0xa) + ").";
		break;
	case 72:	// 4d69
		out = OpY1_eraseFirstCharRef(OpY1_floatToStringSigned(ff4 / c30_ba09e0, 1, 2)) + "% chance to shoot down grenades, rockets, or missiles that pass within a range of " + intToString(3) + ", checked every time the projectile moves. Can also intercept Remote Datajack projectiles.\n <parallel_ok>";
		break;
	case 73:	// 4ede
	{
		int v5d60 = getValue457330(111);
		int v5d64 = getValue457330(112);
		if (v5d64 == -1)
		{
			out = intToString(ff4) + "% chance to reflect " + gameStrings_cf40c8[abs(v5d60)] + " back in the direction of the attack.";
		}
		else
		{
			if (v5d64 == 360)
		{
			out = intToString(ff4) + "% chance to deflect " + gameStrings_cf40c8[abs(v5d60)] + " in a random direction.";
		}
		else
		{
			out = intToString(ff4) + "% chance to redirect " + gameStrings_cf40c8[abs(v5d60)];
			if (v5d60 < 0)
		{
			out += ", preferring to direct them towards a nearby hostile if possible. ";
		}
		else
		{
			out += ". ";
		}
			if (v5d64 > 0)
		{
			out += "Outgoing deflections are limited to a " + intToString(abs(v5d64)) + "-degree arc centered against the angle of attack.";
		}
		else
		{
			out += "Deflections are limited to a " + intToString(abs(v5d64)) + "-degree arc centered in line with the angle of attack.";
		}
		}
		}
		out += " Unable to affect guided projectiles, or any that succesfully penetrate.\n <no_stack>";
		break;
	}
	case 74:	// 544d
		out = "When user damaged by any hostile ranged attack, " + intToString(ff4) + "% chance to immediately teleport towards the attacker, if not already adjacent. Requires an open path to target location.";
		break;
	case 75:	// 5528
		out = intToString(ff4) + "% chance to negate the effects of incoming critical strikes.";
		if (ff4 < 100)
		{
			out += "\n <stacks>";
		}
		break;
	case 76:	// 55df
		out = "Produce energy equivalent to " + intToString(ff4) + "% of all thermal damage sustained.\n <stacks>";
		break;
	case 77:	// 56ba
		out = "Reclaims " + intToString(ff4) + " matter from each attached part destroyed.\n <no_stack>";
		break;
	case 78:	// 5795
		out = "Reduces firing time for an energy gun or cannon by " + intToString(ff4) + "%, if fired alone. Incompatible with Weapon Cyclers and autonomous or overloaded weapons.\n <no_stack>";
		break;
	case 79:	// 5870
		out = "Reduces firing time for any launcher by " + intToString(ff4) + "%, if fired alone. Incompatible with Weapon Cyclers and autonomous or overloaded weapons.\n <no_stack>";
		break;
	case 80:	// 594b
		out = "Reduces collective firing time of all non-melee weapons by " + intToString(ff4) + "%. Incompatible with Quantum Capacitor, Launcher Loader, and autonomous weapons.\n <stacks, capped at " + intToString(30) + "%>";
		break;
	case 81:	// 5ade
		out = "Reduces melee attack time by " + intToString(ff4) + "%.\n <stacks, capped at " + intToString(50) + "%>";
		break;
	case 82:	// 5c71
		out = "Reduces enemy ranged targeting accuracy by " + intToString(ff4) + "%.\n <no_stack>";
		break;
	case 83:	// 5d4c
		out = "Reduces ranged targeting accuracy of all enemies in view by " + intToString(ff4) + "% against all targets.\n <no_stack>";
		break;
	case 84:	// 5e27
		out = "Enables responsive movement to avoid direct attacks, " + intToString(ff4) + "% to dodge while on legs, hovering or flying (no effect on tracked or wheeled movement). Same chance to evade triggered traps, and a +1 to effective momentum for melee attacks and ramming. No effects while overweight.\n <no_stack>";
		break;
	case 85:	// 5f02
		out = "Increases non-melee weapon accuracy by " + intToString(ff4) + "%.\n <stacks>";
		break;
	case 86:	// 5fdd
		out = "Increases non-melee weapon accuracy by " + intToString(ff4) + "% for each weapon fired in a multi-weapon volley, minus one.\n <stacks>\n\nExample: All weapons in a three-weapon volley would have +" + intToString(ff4 << 1) + "% accuracy ((3-1)*" + intToString(ff4) + "=" + intToString(ff4 << 1) + ").";
		break;
	case 87:	// 6305
		out = "Increases non-melee weapon accuracy by " + intToString(ff4) + "% if your previous action was an attack on same target.\n <stacks>";
		break;
	case 88:	// 63e0
		out = "Increases non-melee weapon accuracy by " + intToString(ff4) + "% if target's previous action was an attack on you.\n <stacks>";
		break;
	case 89:	// 64bb
		out = "Increases non-melee weapon accuracy by " + intToString(ff4) + "%, applying benefit to both self and any allies within a range of " + intToString(10) + ".\n <stacks>";
		break;
	case 90:	// 664e
		out = "Increases melee attack accuracy by " + intToString(ff4) + "%, and minimum damage by " + intToString(ff4 / 2) + " (cannot exceed weapon's maximum damage).\n <stacks>";
		break;
	case 91:	// 67f1
		out = "Automatically use active melee weapon to attack any hostile that moves into an adjacent position at 33% of the normal time cost (no follow-ups).\n <no_stack>";
		break;
	case 92:	// 6803
		out = "10% chance to use a melee weapon to deflect each incoming projectile, with a second melee weapon adding 5%, and an additional 2% for each after that. For example, three melee weapons have a collective 17% chance to deflect each projectile. Melee weapons successfully deflecting projectiles in this manner have a 50% chance to take 1 damage each time.\n <no_stack>";
		break;
	case 93:	// 6815
		out = "Increases launcher accuracy by " + intToString(ff4) + "%. Also prevents launcher misfires caused by system corruption.\n <stacks>";
		break;
	case 94:	// 68f0
		out = "Increases accuracy of all attached weapons by " + intToString(ff4) + "%, while also increasing their coverage by " + intToString(100) + "%.\n <no_stack>";
		break;
	case 95:	// 6a83
		out = "Increases weapon critical chances by " + intToString(ff4) + "%. Only affects weapons that are already capable of critical hits, and not applicable for the Meltdown critical.\n <half_stack>";
		break;
	case 96:	// 6b5e
		out = "Increases target core exposure by " + intToString(ff4) + "%. Applies only to gun, cannon, and melee attacks.\n <half_stack>";
		break;
	case 97:	// 6c39
		out = "Increases non-melee weapon accuracy by " + intToString(ff4) + "% <stacks>. Increases target core exposure by " + intToString(ff4) + "%. Reduces enemy ranged targeting accuracy by " + intToString(ff4) + "%.\n <no_stack>";
		break;
	case 98:	// 6e9a
		out = "Enables " + intToString(ff4) + "% chance to bypass target armor, ignoring it for coverage calculation purposes. Does not apply to AOE attacks.\n <no_stack>";
		break;
	case 99:	// 6f75
		out = "Reduces recoil from each weapon in a volley by " + intToString(ff4) + ".\n <stacks>";
		break;
	case 100:	// 7050
		out = "Reduces matter cost of firing any weapon by " + intToString(ff4) + "%.\n <half_stack>";
		break;
	case 101:	// 712b
		out = "Reduces energy cost of firing any weapon by " + intToString(ff4) + "%.\n <half_stack>";
		break;
	case 102:	// 7206
		out = "Increases Sigix non-AOE weapon damage by " + intToString(ff4) + "%. Incompatible with other part-based damage-modifying effects. Also enables resistance against all standard forms of damage: " + intToString(ff4 / 2) + "%. If this part is destroyed, so is its user, and if used by Cogmind, for every 3 damage taken also does 1 damage to Cogmind's core integrity.\n <no_stack>";
		break;
	case 103:	// 73a9
		out = "Increases energy gun/cannon damage by " + intToString(ff4) + "%.\n <half_stack>";
		break;
	case 104:	// 7484
		out = "Consecutive attacks against the same robot class have an increasing chance to calibrate weapons to inflict more serious damage on such targets, increasing non-AOE damage against them by " + intToString(ff4) + "% once calibration is complete.\n <no_stack>";
		break;
	case 105:	// 755f
		out = "Increases ballistic gun/cannon minimum damage by " + intToString(ff4) + "%, and may allow some weapons to exceed their normal maximum damage as well.\n <no_stack>";
		break;
	case 106:	// 763a
		out = "Increases melee weapon maximum damage by " + intToString(ff4) + "%, and decreases melee attack accuracy by " + intToString(ff4 / 5) + "%.\n <half_stack>";
		break;
	case 107:	// 77e0
		out = "Increases effective momentum by " + intToString(ff4) + " for melee attacks and ramming.\n <stacks>";
		break;
	case 108:	// 78bb
		out = "Increases per-weapon chance of follow-up melee attacks by " + intToString(ff4) + "%.\n <half_stack>";
		break;
	case 109:	// 7996
		out = "Expands automatic secondary targeting capability to include volleys composed of any projectile weapons instead of limiting the effect to guns.\n";
		break;
	case 110:	// 79a8
		out = "Increases overloaded energy weapon damage by " + intToString(ff4) + "%.\n <no_stack>";
		break;
	case 111:	// 7a83
		out = "Decreases overloaded energy weapon heat by " + intToString(ff4) + "%.\n <no_stack>";
		break;
	case 112:	// 7b5e
		out = "Increases salvage recovered from targets, +" + intToString(ff4) + " modifier. Compatible only with gun-type weapons that fire a single projectile.\n <stacks>";
		break;
	case 113:	// 7c39
		out = "Increases salvage recovered from targets, +" + intToString(ff4) + " modifier. Compatible only with gun- or cannon-type weapons that fire a single projectile.\n <stacks>";
		break;
	case 114:	// 7d14
		out = "Enables full recovery of all salvagable parts from a target, which take no further damage from the salvaging process and cannot be fried, melted, or corrupted. No effect on matter recovery, and cannot interfere with self-destruction routines.";
		break;
	case 115:	// 7d26
		out = "Holds target in place. Beam strength: " + intToString(ff4) + ". Also cancels a flying/hovering target's 10%/5% bonus to dodge for the duration.";
		break;
	case 116:	// 7e01
		out = "Ignore all effects of stasis beams and stasis traps.";
		break;
	case 117:	// 7e13
		out = "Holds targets in place. Also cancels a flying/hovering target's 10%/5% bonus to dodge for the duration.";
		break;
	case 118:	// 7e25
		out = intToString(OpX5_minInt(ff4 * f4c, 35)) + "% chance to crush robots when ramming them. Cannot crush targets of large or greater size, or those with more than " + intToString(50) + " core integrity.\n <stacks, capped at " + intToString(35) + "%>";
		break;
	case 119:	// 8045
		out = "Penetrates target robot just enough to enable system access for hacking. Also a base " + intToString(50) + "% chance to rewire temporarily disabled hostiles, further modified by any offensive hackware. Can be used to parse almost any robot system. Many more hacking options available after using a RIF Installer inside a Garrison, and with Relay Couplers.";
		break;
	case 120:	// 8115
		if (ff4 == 3)
		{
			out = "On impact, " + intToString(getValue457330(126)) + "% chance to interact with target system to cause random chaotic effects. Effect will not trigger on Special class targets.";
		}
		else
		{
			out = "Performs a random hack on any standard 0b10 Swarmer, Cutter, Grunt, Brawler, Duelist, Sentry, Demolisher, Specialist, Hunter, Heavy, Carrier, or Behemoth variant.";
			if (ff4 == 2)
		{
			out += " Alternatively may instead randomly cause other chaotic effects of mysterious origin.";
		}
		}
		break;
	case 121:	// 822f
		out = "Increases chance of successful machine hack by " + intToString(ff4) + ". Also provides a +" + intToString(ff4 / 2) + "% bonus to rewiring traps and disrupted robots.\n <stacks>";
		break;
	case 122:	// 83d2
		out = "While hacking machines, reduces both chance of detection and rate of detection chance increases by " + intToString(ff4) + ". Reduces tracing progress advances by the same amount. Also a lower chance that hacking machines will be considered serious enough to trigger an increase in security level, and reduces central database lockout chance by " + intToString(ff4 / 2) + "%. Blocks hacking feedback side effects " + intToString(OpX5_minInt(ff4 << 1, 100)) + "% of the time, and repels " + intToString(ff4 << 1) + "% of hacking attempts against allies within a range of " + intToString(10) + ".\n <stacks>";
		break;
	case 123:	// 87c2
		out = "While attached during Fabricator operation, loading and building a single schematic will not be detected or traced.";
		break;
	case 124:	// 87d4
		out = "Enables additional robot hacks when used in conjunction with RIF and Datajack. Requires having used a RIF Installer inside a Garrison.";
		break;
	case 125:	// 87e6
		out = intToString(ff4) + "% chance to instantly assimilate any robot without disruption immunity. No effect on unpowered, unconnected, or broken bots.";
		break;
	case 126:	// 8881
		out = "Initializes a dimensional slip node at the current position. Transdimensional reconstruction automatically targets the nearest active slip node, regardless of distance.\n <consumed>";
		break;
	case 127:	// 8893
		out = "Teleports the user to an approximate distance of " + intToString(abs(ff4)) + " from current position, traveling along dimensional pathways of least resistance.";
		if (ff4 < 0)
		{
			out += " Simultaneously teleports all visible robots within a range of " + intToString(10) + " from the origin, and ignores any form of teleport-inhibiting technology.";
		}
		out += " Any pursuers at the time lose tracking on the user.\n <consumed>";
		break;
	case 128:	// 8a5e
		out = (ff4 == 1 ? string("Evolves a new slot of a random type.") : "Evolves " + intToString(ff4) + " new slots of random types.\n <consumed>");
		break;
	case 129:	// 8c3c
		out = "Restores " + intToString(ff4) + "% of core integrity.\n <consumed>";
		break;
	case 130:	// 8d17
		out = "Drains a core at or above half integrity to restore integrity of all attached parts at a 1:" + intToString(ff4) + " ratio. Process is reversed for cores below half integrity. Neither core nor parts can be dropped below " + intToString((int)(c30_ba0bb4 * 100.0)) + "% integrity by this process.\n <consumed>\n\nExamples: A drain of 100 core integrity is capable of repairing " + intToString(ff4 * 0x64) + " part integrity. A drain of " + intToString(ff4 * 0x64) + " part integrity is capable of repairing 100 core integrity.";
		break;
	case 131:	// 9046
		out = "Permanently increases core heat dissipation by " + intToString(ff4) + ".\n <consumed>";
		break;
	case 132:	// 9127
		out = "Permanently increases core energy generation by " + intToString(ff4) + ".\n <consumed>";
		break;
	case 133:	// 9202
		out = "Energy and matter required for part attachment permanently reduced by " + intToString(ff4) + "%. Also enables " + intToString(50) + "% chance to avoid negative effects of attaching a faulty prototype or corrupted part, but this feature requires 20 matter to take effect.\n <no_stack>";
		break;
	case 134:	// 9395
		out = "Permanently adds automated ability which converts core to matter. If matter capacity is at least " + intToString(300) + ", in any turn during which current matter falls below " + intToString(100) + ", gain " + intToString(200) + " matter at the cost of " + intToString(10) + " max core integrity. Functionality does not consider non-attached containers, and ceases if at any point max core falls below " + intToString(500) + ".\n <consumed>";
		break;
	case 135:	// 974e
		out = "Provides permanent immunity against system corruption.\n <consumed>";
		break;
	case 136:	// 9760
		out = "Converts all heat above " + intToString(ff4) + " to energy every turn at a " + intToString(ff8) + ":1 ratio.\n" + (f44 == 19 ? " <consumed>" : " <no_stack>") + "\n\nExample: At 400 heat precisely " + intToString(400 - ff4) + " heat would be used to generate " + intToString((400 - ff4) / ff8) + " energy ((400-" + intToString(ff4) + ")/" + intToString(ff8) + "=" + intToString((400 - ff4) / ff8) + ").";
		break;
	case 138:	// 9d9c
		out = "Removes all corruption and wipes entire memory, including part knowledge, robot analysis, schematics, and map data. Also restores knowledge of alien technology.\n <consumed>";
		break;
	case 137:	// 9dae
		out = "Upgrades subspace navigation controls.\n <consumed>";
		break;
	case 139:	// 9dc0
		out = "Destroys all walls and earth up to a distance of " + intToString(ff4) + " without affecting other materials.\n <consumed>";
		break;
	case 140:	// 9e9b
		out = "If on the ground at current position use > or right-click on self to detonate.\n";
		break;
	case 141:	// 9ead
		out = "Duplicates object at current location.\n <consumed>";
		break;
	case 142:	// 9ebf
		out = "Permanently increases maximum core integrity by " + intToString(ff4) + ".\n <consumed>";
		break;
	case 143:	// 9f9a
		out = "Permanently increases inventory capacity by " + intToString(ff4) + ".\n <consumed>";
		break;
	case 144:	// a075
		out = "Permanently increases energy capacity by " + intToString(ff4) + ".\n <consumed>";
		break;
	case 145:	// a150
		out = "Permanently increases matter storage capacity by " + intToString(ff4) + ".\n <consumed>";
		break;
	case 146:	// a22b
		out = "Permanently increases mass support by " + intToString(ff4) + " (regardless of propulsion).\n <consumed>";
		break;
	case 147:	// a306
	{
		vector<int> list;
		unknown56fc30(list);
		vector<string> parts;
		for (unsigned int i = 0; i < list.size(); i++)
		{
			if (list[i] != 100)
			{
				string part = gameStrings_d323f8[i] + " " + OpY1_intToStringSigned(100 - list[i]) + "%";
				parts.push_back(part);
			}
		}
		out = "Modifies base damage ";
		out += (parts.size() > 1 ? "resistances: " : "resistance: ");
		out += parts[0];
		for (unsigned int j = 1; j < parts.size(); j++)
			out += ", " + parts[j];
		out += ".\n <stacks, consumed>";
		break;
	}
	case 148:	// a5b6
		out = intToString(ff4) + "% chance to identify a random unidentified part in inventory each turn. Cannot identify alien technology.\n <parallel_ok>";
		break;
	case 149:	// a651
		out = "Each turn identifies all unidentified items in view, both in the open and attached to robots. Cannot identify alien technology.";
		break;
	case 150:	// a663
		out = "While active, internalizes information about any identified items seen in the open or used by robots, attempting to create new relevant schematics over time based on that knowledge.";
		break;
	case 151:	// a675
		out = OpY1_eraseFirstCharRef(OpY1_floatToStringSigned((ff4 / c30_ba0a88) * 100.0, 1, 2)) + "% chance each turn to purge 1% of system corruption, losing " + intToString(3) + " integrity each time the effect is applied.\n <parallel_ok>";
		break;
	case 152:	// a7f0
		out = "Decodes ambient 0b10 transmissions to extract bits of useful data over time. " + string((ff4 == 0 ? "This variant is tuned to prioritize info about items, traps, exits, hidden doorways, interactive machines, and active patrol and security positions." : (ff4 == 1 ? "This variant is tuned to prioritize info about items." : (ff4 == 2 ? "This variant is tuned to prioritize info about traps, exits, garrisons, and hidden doorways." : "This variant is tuned to prioritize info about garrisons and active patrol, investigation, reinforcement, and security positions.")))) + "\n <parallel_ok>";
		break;
	case 153:	// a934
		out = "Converts energy to matter at a ratio of " + intToString(ff8) + ":" + intToString(ff4) + " every turn, in other words consuming " + intToString(ff8) + " energy to create " + intToString(ff4) + " matter.\n <parallel_ok>";
		break;
	case 154:	// ac58
		out = "Converts matter to energy at a ratio of 1:" + intToString(ff4) + " every turn, in other words consuming 1 matter to create " + intToString(ff4) + " energy.\n <parallel_ok>";
		break;
	case 155:	// adf6
		out = "Generates 1 energy per " + intToString(ff4) + " surplus heat every turn.\n <parallel_ok>";
		break;
	case 156:	// aed1
		out = "Automatically collects matter within a range of " + intToString(ff4) + ".";
		if (ff8 != 0)
		{
			out += " Ignores all obstacles and does not require line of sight.";
		}
		break;
	case 157:	// afc8
		out = "Attracts any debris within at least a range of " + intToString(ff4 - 2) + ", converting it to matter on arrival.";
		break;
	case 158:	// b0a6
		break;
	case 159:	// b0ab
		out = "Recycles all adjacent items into matter (" + intToString(ff4) + "% efficiency).";
		break;
	case 160:	// b186
		out = "Activate a second time to begin automatically collecting parts at current location to recycle them into matter (" + intToString(ff4) + "% efficiency) at a rate of " + intToString(ff4 / 10) + " per turn. Can hold no more than " + intToString(f50 * 0x32) + " scrap at a time.\n <parallel_ok, resume_ok>";
		break;
	case 161:	// b3ef
		out = "Automatically cannibalizes a part on the ground to restore " + intToString(10) + " integrity to the most damaged attached part of the same subtype, up to no more than " + intToString((int)(c30_bba054 * 100.0)) + "% of maximum integrity." + (ff4 != 0 ? " Unable to use or repair parts marked non-repairable, or unique parts, but may use and repair prototypes." : " Unable to use or repair parts marked non-repairable, or any prototypes or unique parts.") + " Also provides active maintenance of attached Overtuned parts to prevent malfunctions (function available even if powered off). If part on the ground is an identified gun/cannon/melee weapon and currently have an empty weapon slot, instead attaches it at no cost.";
		if (ff4 == 0)
		{
			out += " Cannot attach prototypes.";
		}
		break;
	case 162:	// b64a
		out = OpY1_eraseFirstCharRef(OpY1_floatToStringSigned(((float)ff4 / c30_ba0b60) * 100.0, 1, 2)) + "% chance each turn to restore a broken or malfunctioning part, attached or in inventory, to functionality. Unable to repair alien technology, or prototypes above rating 8, and no effect on corrupted or faulty parts, only those currently marked \"Broken\".\n <parallel_ok>";
		break;
	case 163:	// b70d
		out = OpY1_eraseFirstCharRef(OpY1_floatToStringSigned(((float)ff4 / c30_ba0b60) * 100.0, 1, 2)) + "% chance each turn to convert a faulty prototype, attached or in inventory, into a working version. Operation requires having at least two of the same prototype, even if both are faulty.\n <parallel_ok>";
		break;
	case 164:	// b7d0
		out = "While active, move into 0b10 machines to repair a piece. Target's interactive part must be intact.\n\nCan also move into a Terminal's interactive part to reconfigure it, wiping all direct hacks and applying a modifier to all subsequent indirect hacks, but causing tracing to begin immediately.\n\nEither action costs " + intToString(ff4) + " matter and " + intToString(2) + " turns.";
		break;
	case 165:	// b963
		out = "While active, repeatedly move into a machine or blast door to dismantle it, where targets with higher armor take longer to dismantle. Each step of the process takes " + intToString(ff4) + " turns, and progress is reported as the number of turns remaining to complete dismantling. Dismantling an explosive machine takes it apart without triggering an explosion.";
		break;
	case 166:	// ba3e
		out = "Enables " + intToString((f50 * 0xa) + 40) + "% chance to extract a non-hostile trap at current location, adding it to the extractor inventory if possible. Can hold up to " + intToString(ff4) + " traps of the same type, but cannot store stasis traps. Each extraction attempt requires " + intToString(5) + " matter. Activate a second time to begin dropping stored traps to the ground at a rate of one per turn. Also prevents user system corruption from accidentally triggering a trap at current location due to movement.";
		break;
	case 167:	// bc97
		out = (ff4 == 1 ? "Holds 1 " + getRecord()->f1ac + ". " : "Holds up to " + intToString(ff4) + " " + getRecord()->f1ac + "s. ") + "Launched when bay is activated. Matching drones operate as long as this bay is functional and attached, though it does not have to remain active. Additional available bays in inventory can also receive returning drones as long as one already attached. Damaged drones are repaired on retrieval by using the bay's integrity as a resource, at a cost of " + intToString(5) + " to repair any core damage and " + intToString(2) + " for each damaged or missing part. Repairs cannot drop bay integrity below " + intToString(10) + ", at which point a bay cannot retrieve damaged drones.";
		break;
	case 168:	// c25b
		out = "Fabricates a random derelict part at a rate of 1 per " + (ff4 > 1 ? intToString(ff4) + " turns." : string(" turn.")) + "\n <parallel_ok, resume_ok>";
		break;
	case 169:	// c46f
		out = "Fabricates a " + f1b4 + " at a rate of 1 per " + (ff4 > 1 ? intToString(ff4) + " turns." : string(" turn.")) + "\n <parallel_ok, resume_ok>";
		break;
	case 170:	// c70c
		out = "Fabricates a random Assembled at a rate of 1 per " + (ff4 > 1 ? intToString(ff4) + " turns." : string(" turn.")) + "\n <parallel_ok, resume_ok>";
		break;
	case 171:	// c920
		out = "Fabricates a random drone at a rate of 1 per " + (ff4 > 1 ? intToString(ff4) + " turns." : string(" turn.")) + " Fabricated drones disintegrate after " + intToString(100) + " turns, or upon being disarmed.\n <parallel_ok, resume_ok>";
		break;
	case 172:	// cbed
		out = "Fabricates a random turret at a rate of 1 per " + (ff4 > 1 ? intToString(ff4) + " turns." : string(" turn.")) + " Requires sufficient space to deploy, where if no suitable location is available the build will be temporarily halted just before deployment.\n <parallel_ok, resume_ok>";
		break;
	case 173:	// ce00
		out = (f8 == "Heart of Steel" ? string("Undergoes a transformaton") : "Releases " + opw8_countString(ff8, g_d25de0[OpU8a_indexOfName4(g_d25de0, f1b4)]->f1ac));
		out += " after remaining active for " + intToString(ff4) + " turns.\n <parallel_ok, resume_ok>";
		break;
	case 174:	// d0a2
		out = "Autonomous self-powered unit capable of building and maintaining a complete Golem. Construction requires approximately " + intToString(900) + " turns.";
		break;
	case 175:	// d175
		out = "Attracts any loose items within at least a range of " + intToString(ff4 - 2) + ", even if they have to be drawn through solid materials to arrive. Each turn the process damages each item it affects by 1% of max integrity or 1, whichever is greater.";
		break;
	case 176:	// d253
		out = "Every " + intToString(5) + " turns emits a powerful signal tuned to power down all Assembled within a range of " + intToString(ff4) + ".";
		break;
	case 177:	// d3e6
		out = "Every " + intToString(5) + " turns emits a powerful signal that befriends all visible Subdwellers within a range of " + intToString(ff4) + ".";
		break;
	case 178:	// d579
		out = "Calls Wizards to aid you.\n <no_stack>";
		break;
	case 179:	// d58b
		out = (ff4 < 10 ? "Regenerates integrity at a rate of 1 per " + intToString((10 - ff4) + 1) + " turns.\n <parallel_ok, resume_ok>" : (f48 == 3 && (int)fb4 ? "Regenerates integrity at a rate of " + intToString(ff4 - 9) + " per turn. Must be active, and requires " + intToString((int)fb4) + " energy.\n <parallel_ok>" : "Regenerates integrity at a rate of " + intToString(ff4 - 9) + " per turn.\n <parallel_ok>"));
		break;
	case 180:	// dbaa
		out = "Repairs itself by cannibalizing any part on the ground at current position, restoring integrity by " + intToString(100 / ff4) + "% of that of the source, or " + intToString((int)((100 / ff4) * c30_ba0a8c)) + "% if the source is armor.";
		break;
	case 181:	// dd6b
		out = "Excavates all adjacent walls and earth.";
		break;
	case 182:	// dd7d
		out = "Converts each adjacent wall, earth, and door to " + intToString((int)(ff4 * 0.5)) + "-" + intToString((int)(ff4 * 1.5)) + " energy.";
		break;
	case 183:	// df31
		out = "Sets a temporal reversion point when attached, then loses " + intToString(ff4) + " integrity per turn. Once integrity is depleted naturally, you are forced back to that point in time. If destroyed prematurely the reversion will not occur.";
		break;
	case 184:	// e00c
		out = "Automatically locates and opens all doors within view, whether operated by door terminals or not.";
		break;
	case 185:	// e01e
		out = "Automatically hacks visible door terminals within a range of " + intToString(10) + ". Requires being within that range for " + opw8_countString(ff4, "turn") + ".";
		break;
	case 186:	// e1e1
		out = "Automatically and instantly reprograms visible hostile traps within a range of " + intToString(ff4) + ".";
		break;
	case 187:	// e2bc
		out = "While active, eventually teleports to a random nearby location, removing some attached part in the process, but possibly restoring one as well if suitable slots are available.";
		break;
	case 188:	// e2ce
		out = "Intermittently transforms attached parts into different parts. Resulting parts retain the same percentage integrity as the former part, but also recover " + intToString(ff4) + "% of any missing amount.\n <parallel_ok>";
		break;
	case 189:	// e3a9
		out = "Prevents movement by any robot within a range of " + intToString(ff4) + ".";
		break;
	case 190:	// e484
		out = "Prevents core/hover/flight speed of all hostiles in view within a range of " + intToString(ff4) + " from exceeding " + (g_d28d16 ? intToString(50) : intToString(200) + "%") + ".\n <no_stack>";
		break;
	case 191:	// e74f
		out = "Enables greater freedom during assignment of evolution parameters. No effect after reaching maximum slot count (26).";
		break;
	case 192:	// e761
		out = "Move through up to " + intToString(ff4) + " consecutive solid objects to the first open space on the other side, in the process taking core integrity damage equivalent to 1% of maximum for each space traveled.";
		break;
	case 193:	// e83c
		out = "Warp across any number of open spaces nearly instantly, taking " + intToString(ff4) + " damage to core integrity for each space traveled.";
		break;
	case 194:	// e917
		out = "Core loses " + intToString((int)(ff4 * 0.5)) + "-" + intToString((int)(ff4 * 1.5)) + " integrity with each discharge.";
		break;
	case 195:	// eacb
		out = "Splits robots into constituent parts on " + intToString(ff4) + "% of successful hits.";
		break;
	case 196:	// eba6
		out = "Disables one hover or flight propulsion component with each hit. No effect on targets with innate disruption immunity.";
		break;
	case 197:	// ebb8
		out = "Stand on a power source and use > or right-click on self to convert it into a proximity mine that detonates when any enemy moves adjacent to it. Rigging requires " + intToString(ff4) + " matter. Repeat the process to manually start a timer to detonate the power source after " + intToString(8) + " turns.";
		break;
	case 198:	// ed4b
		out = "While active, move into explosive machines to rig them to detonate whenever any 0b10 combat robot passes. Rigging requires " + intToString(ff4) + " matter.";
		break;
	case 199:	// ee26
		out = "While active, move into adjacent robots to assimilate and convert them to Borg form. Starting the process is a " + intToString(3) + "-turn action, unaffected by any melee attack time modifiers. Higher-rated targets are harder to assimilate, and the conversion takes longer, but always at least " + intToString(12) + " turns. The matter cost to assimilate increases significantly with the current number of Borg allies. Borg regenerate both core and parts at a rate that also increases with the number of Borg allies. Similarly, " + f24 + " regenerates itself over time via the same principle. Losing a Borg ally causes core damage to self, the amount dependent on robot tier. If insufficient remaining core, " + f24 + " is destroyed instead. Removing or otherwise losing this part causes all Borg allies to form their own collective.";
		break;
	case 200:	// f0b8
		out = "Doubles Borg core and part regeneration rate.\n <no_stack>";
		break;
	case 201:	// f0ca
		break;
	case 202:	// f0cf
		out = "On hitting a robot, draws up to " + intToString(3) + " nearby objects to attack it. " + intToString(15) + "% chance to instead pull target to self if path is clear, then immediately allowed to act again. Also a separate " + intToString(20) + "% chance to instantly crush targets of medium size and below which have no more than 50 remaining core integrity.";
		break;
	case 203:	// f30f
		out = "";
		break;
	case 204:	// f321
		out = "";
		break;
	case 205:	// f333
		out = "";
		break;
	case 206:	// f345
		out = "";
		break;
	case 207:	// f357
		out = "Selects its own targets and attacks them if in range, at no time cost to you.";
		break;
	case 208:	// f369
		out = "If on the ground at current position use > or right-click on self to start timer. Automatically detonates after " + intToString(ff4) + " turns.\n";
		break;
	case 209:	// f444
		break;
	case 210:	// f449
		out = "Enables long-distance communication with Warlord forces to determine their composition and hiding locations. Toggle active state to temporarily list all squads in the area. If active while near a squad, will signal it to emerge and assist.";
		break;
	case 211:	// f45b
		out = "While active, modifies constructs and expands or builds new ones if empty power, propulsion, or weapon slots are available, if enough resources have been collected. Activate a second time to begin automatically collecting useful parts at current location to generate resources. While in COLLECT mode, visible parts suitable as resources flash on the map. Toggling that mode on also temporarily displays its current list of contained resources.";
		break;
	case 212:	// f46d
	{
		vector<int> slots(4u,0);
		vector<int> list;
		vector<string> parts;
		c30_split(f1b4,'|',parts);
		for (unsigned int i = 0; i < parts.size(); i++)
		{
			string inside;
			if (opU1_extractParens(parts[i],inside))
			{
				int idx = OpT8a_findStringIndex(gameStrings_d30428,4,parts[i]);
				slots[idx] += stringToInt(inside);
			}
		}
		out = "When attached, gives access to additional temporary ";
		out += (OpT8a_sumVector(slots) > 1 ? "slots: " : "slot: ");
		int n = 0;
		for (unsigned int j = 0; j < slots.size(); j++)
		{
			if (slots[j] != 0)
			{
				if (n != 0)
					out += ", ";
				out += gameStrings_d378d0[j] + " x" + intToString(slots[j]);
				n++;
			}
		}
		out += ".";
		if (f48 != 3)
			out += " Temporary slots disappear if this part is removed, or if their contents are removed. Under some circumstances, it is normal for temporary slots to take an extra moment to fully disappear. Large parts may not occupy temporary slots.";
		break;
	}
	case 213:	// f7d5
		out = "If active while moving over free matter, repairs itself at a cost of " + intToString(ff4) + " matter per 1 integrity. Will only consume up to half available matter if owner's matter stores not currently full.";
		break;
	case 214:	// f8b0
		break;
	case 215:	// f8b5
		out = "While active, moving towards a wall, earth, or machine automatically disintegrates it. " + (ff4 != 0 ? "Requires at least " + intToString(ff4) + " momentum. Energy upkeep: 8." : string("Energy upkeep: 6."));
		break;
	case 216:	// faf8
		out = (getValue457330(117) == 1 ? "While active and charged, move to teleport in a general direction to an approximate distance of " + intToString(abs(ff4)) + " from current position. May not arrive at destination entirely in one piece." : "While active, move to teleport in a general direction to an approximate distance of " + intToString(abs(ff4)) + " from current position. Will not arrive at destination entirely in one piece.\n <consumed>");
		break;
	case 217:	// fdf3
		out = "While active, intermittently and automatically attempts to teleport user a distance of approximately " + intToString(ff4) + "-" + intToString(ff8) + ", where direction is influenced by relative position across short but random intervals in time. Any pursuers at the time lose tracking on the user, but subspace disturbance upon arriving at destination alerts nearby robots to investigate. If inactive while attached, loses 1 integrity per turn.";
		break;
	case 218:	// ff8e
		out = "Offers some clarity as to X0-1V1's current mood and level of amusement. X0-1V1's amusement also falls somewhat more quickly over time if not keeping an eye on it with this active.";
		break;
	default:
		out = "(Missing effect description)";
	}
}
